#!/usr/bin/env node
// Export aligned lyric timings for the album page's player.
// Reads videos/NN-*/lyrics.json and writes ../../lyrics-sync.js:
//   window.LYRIC_SYNC = { "<track n>": [[section, start, end, [[word, start], ...]], ...] }
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const videos = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = {};
for (const d of readdirSync(videos).filter((d) => /^\d\d-/.test(d)).sort()) {
  const f = join(videos, d, "lyrics.json");
  if (!existsSync(f)) continue;
  const { lines } = JSON.parse(readFileSync(f, "utf8"));
  out[String(parseInt(d, 10))] = lines.map((l) => [
    l.section,
    +l.start.toFixed(2),
    +l.end.toFixed(2),
    l.words.map((w) => [w.w, +w.start.toFixed(2)]),
  ]);
}
const js = "// Generated by videos/_tools/export-lyrics.mjs — lyric timings aligned to the vocals.\nwindow.LYRIC_SYNC=" + JSON.stringify(out) + ";\n";
writeFileSync(join(videos, "..", "lyrics-sync.js"), js);
console.log(`lyrics-sync.js: ${Object.keys(out).length} tracks, ${(js.length / 1024).toFixed(1)} KB`);
